name: Multiple Jobs

on:
 push:

jobs:
  test:
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v4
     - run: echo "Testing"

Deploy:
   needs: test
   runs-on: ubuntu-latest

   steps:
   -run: echo "Deploying,only if test passed"
